### ISSUE TITLE
question

### ISSUE THREAD

**Issue by yizhipan** [NITR098/Awesome-U-Net#10]
In the preparation of the data set, in the prepare_segpc.ipynb file, the specific settings of the sim_resize and resize_pad functions are not given. When I run it, I get an error NameError: name 'sim_resize' is not defined And NameError: name 'resize_pad' is not defined.Please tell me how to solve it, thank you

**Comment by SusmitaSenGhosh** [comment]
Hey @yizhipan , how did you solve the problem? I am facing the same issue. Thanks in advance.

**Comment by yizhipan** [comment]
> Hey @yizhipan , how did you solve the problem? I am facing the same issue. Thanks in advance.

"These code details can be found in their previous work; I just can't recall the specifics at the moment."
