### ISSUE TITLE
Path of the datasets

### ISSUE THREAD

**Issue by Eveinn** [NITR098/Awesome-U-Net#2]
Which file needs to be modified for the path to the dataset? Take UNet as an example, I changed the dataset path in line 41 of isic.py（And config file）, but it still reports an error, showing "FileNotFoundError: [Errno 2] No such file or directory: 'D:/Dataset/ISIC2018/np/X_tr_224x224.npy'"

**Comment by Eveinn** [comment]
` self.data_dir = data_dir if data_dir else "D:/Dataset/ISIC2018"
        self.imgs_dir = os.path.join(self.data_dir, "ISIC2018_Task1-2_Training_Input")
        self.msks_dir = os.path.join(self.data_dir, "ISIC2018_Task1_Training_GroundTruth")`

**Comment by Eveinn** [comment]
` self.data_dir = data_dir if data_dir else "D:/Dataset/ISIC2018"
self.imgs_dir = os.path.join(self.data_dir, "ISIC2018_Task1-2_Training_Input")
self.msks_dir = os.path.join(self.data_dir, "ISIC2018_Task1_Training_GroundTruth")`

**Comment by afshinbigboy** [comment]
For ISIC2018 you can use 2 different Dataset classes:
- [ISIC2018Dataset](https://github.com/NITR098/Awesome-U-Net/blob/0fd543a401e336726f09850e73c1a8669ee02f26/datasets/isic.py#L34): This class loads and prepares images one by one. So you do not need any preparation, but be aware in the dataset path you should have these two folders:
  - ISIC2018_Task1-2_Training_Input
  - ISIC2018_Task1_Training_GroundTruth
- [ISIC2018DatasetFast](https://github.com/NITR098/Awesome-U-Net/blob/0fd543a401e336726f09850e73c1a8669ee02f26/datasets/isic.py#L85): When you have enough memory space you can use this class to speed up the process. To use this class you need to use [`prepare_isic.ipynb`](https://github.com/NITR098/Awesome-U-Net/blob/main/datasets/prepare_isic.ipynb) to create the required NumPy files (_They are containing all images and masks in two files. `X_*.npy` and `Y_*.npy`_). 
Then you should put the path of the folder that contains these two files as `data_dir`. 
(_If you will change the name of files in `prepare_isic.ipynb` you also need to change the file names in lines 93 and 94 of `isic.py`._)

I hope this description can help you.

**Comment by Eveinn** [comment]
Thank you for your reply. I used the first method（ISIC2018Dataset）, but it still fails to run, and it is displayed as“RuntimeError: [enforce fail at ..\c10\core\CPUAllocator.cpp:79] data. DefaultCPUAllocator: not enough memory: you tried to allocate 60115394560 bytes.”, but the GPU is free. The code I modified is lines 107-109.`tr_dataset = ISIC2018Dataset()
vl_dataset = ISIC2018Dataset()
te_dataset = ISIC2018Dataset()`

**Comment by Eveinn** [comment]
Thanks for your reply, I successfully ran the train file yesterday, and I want to know how to evaluate and visualize, can you give me some help? How do I load **_best_model_state_dict.pt_** into the test network for visualization?Thank you very much!

**Comment by afshinbigboy** [comment]
You can comment or remove the training lines if you don't want to train and just need to test. For instance in [`unet-isic.py`](https://github.com/NITR098/Awesome-U-Net/blob/main/train_and_test/isic/unet-isic.py) training and its evaluation lines are 423, 442, 443. (_You can also make comments on lines 389-449._)
From 460 to 469 **_best_model_state_dict.pt_** will load and in 477 it will be evaluated. so you need to print line 478 to see the result numbers. From 537 till the end is for visualization and it will run and then save the `best_model` results on the test images in [`save_imgs_dir`](https://github.com/NITR098/Awesome-U-Net/blob/e62d647f4e63bb849dbf88638ed18b1c1786c048/train_and_test/isic/unet-isic.py#L556)
