### ISSUE TITLE
torchvision version 

### ISSUE THREAD

**Issue by apz719** [NITR098/Awesome-U-Net#4]
Hi
may I ask which version of torchvision did you use in your code? I use 0.6.0 and some features of this have changed, so I do not know which version to use. Thank you very much!

**Comment by NITR098** [comment]
Hello,
Thanks for reaching us. For our experiments, the torch dependent packages versions are as follows:
torch == 1.12.1
torchvision == 0.13.1

> Hi may I ask which version of torchvision did you use in your code? I use 0.6.0 and some features of this have changed, so I do not know which version to use. Thank you very much!
